### ISSUE TITLE
Calls to get-nym for IDUnion Test Ledger are often extremely slow

### ISSUE THREAD

**Issue by dennisn00** [hyperledger/indy-cli-rs#11]
I am running this:
```
pool create idunion_test gen_txn_file=./idunion_test.txn"
pool connect idunion_test
ledger get-nym did=PZvmob8HMGofX5xJPryZvh
```
The DID is a random DID I found in the [TX Explorer](https://idunion.esatus.com/txs/IDunion_Test/domain). I have tried several and the behaviour is the same.
The genesis file I used is from [here](https://raw.githubusercontent.com/IDunion/indy-did-networks/main/networks/idunion/test/pool_transactions_genesis.json)

I then repeat the call to `ledger get-nym` (the `pool create` and `pool connect` is only performed once).
What I am seeing is that the call to `ledger get-nym` takes from a few hundred milliseconds to 1 minute or longer to return, where the later is not rare. I would say around 70% of requests take 20 seconds or longer and maybe 10% result in a message `Transaction response has not been received`. 
I wanted to make sure that this is not an issue with my computer, so I tried it with another machine and got the same result.
I also tried to resolve the same DIDs using the same Genesis File with the [Universal Resolver](https://github.com/decentralized-identity/universal-resolver), and that works fine with 90% of responses after less than 200 ms and max. response time of around 800 ms. 

I assume that that is not how indy-cli-rs is supposed to behave. Am I doing something wrong or is this an issue with indy-cli-rs?

**Comment by WadeBarnes** [comment]
I'm thinking this might have to do with the version of `indy-vdr` being used and how it deals with pool connections and caching.  We've identified similar performance issues in other applications and traced it back to `indy-vdr`.  I believe those issue has since been fixed in `indy-vdr`.

A some questions to get some additional details:
- How does the genesis file compare to the live network?  Are there any nodes listed in the genesis file that no longer exist on the live network?
- Are there any nodes on the live network that are/were not responding to client requests at the time you performed the tests?

**Comment by dennisn00** [comment]
Thanks for the quick response. I am not sure how to check for which nodes still exist in the live network and which respond to client requests. Is there a indy-cli-rs command for this?

**Comment by WadeBarnes** [comment]
You could use the API in [indy-node-monitor](https://github.com/hyperledger/indy-node-monitor) to get a list of the nodes on the network and determine if there are any issues.

You'll need to add entries for the IDunion ledgers to the networks list; https://github.com/hyperledger/indy-node-monitor/blob/main/fetch-validator-status/networks.json

You can then start just the API by running:
```
./manage build
./mange start indy-node-monitor
```

You'll then be able to query the network using the API interface:
![image](https://github.com/hyperledger/indy-cli-rs/assets/10504350/7164f85c-1152-4688-ad3e-5579d835cfcd)

**Comment by WadeBarnes** [comment]
If you have a DID on the network(s) with enough privileges you can query the network using the indy-cli command `ledger get-validator-info`.  Though the output from `indy-node-monitor` is more useful and `indy-node-monitor` allows you to get basic information anonymously.

**Comment by dennisn00** [comment]
I used `indy-node-monitor` and queried it for each node listed in the [genesis file](https://raw.githubusercontent.com/IDunion/indy-did-networks/main/networks/idunion/test/pool_transactions_genesis.json). Out of the 9 nodes, 6 had the `status.ok = true`, but three (siemens, Commerzbank, DeutscheBahn) returned `Error 400: Bad Request: [siemens/Commerzbank/DeutscheBahn] is not a member of IDUnion Test Network." `

**Comment by swcurran** [comment]
@WadeBarnes — is there a way to generate your own genesis file?  I recall there was a way to see that — but can’t remember the tool.  @dennisn00 — its a list of the “Pool” ledger transactions.

**Comment by WadeBarnes** [comment]
> @WadeBarnes — is there a way to generate your own genesis file? I recall there was a way to see that — but can’t remember the tool. @dennisn00 — its a list of the “Pool” ledger transactions.

@swcurran, @dennisn00, Using the `indy-node-monitor` API call `/networks/{network}/pool/transactions`.  The result can be saved and used as a genesis file.

**Comment by WadeBarnes** [comment]
> I used `indy-node-monitor` and queried it for each node listed in the [genesis file](https://raw.githubusercontent.com/IDunion/indy-did-networks/main/networks/idunion/test/pool_transactions_genesis.json). Out of the 9 nodes, 6 had the `status.ok = true`, but three (siemens, Commerzbank, DeutscheBahn) returned `Error 400: Bad Request: [siemens/Commerzbank/DeutscheBahn] is not a member of IDUnion Test Network." `

This is supporting the `indy-vdr` theory.  The missing nodes are likely being included in pool connections/queries and causing the delays.  This is consistent with the performance issues we've identified in other applications with older versions of `indy-vdr`.

@dennisn00, As a test, create a new genesis file using the API above, and see if the performance is better and more stable.

**Comment by dennisn00** [comment]
Yes, using the new Genesis File it runs perfectly!

**Comment by WadeBarnes** [comment]
Great, that confirms the issue.

**Comment by WadeBarnes** [comment]
I've entered a separate ticket to upgrade indy-vdr.  @dennisn00, please close this ticket if you feel we've covered the issue in sufficient detail.

**Comment by dennisn00** [comment]
Ok, thank you for the quick help!
